fail_fast: true

repos:
  - repo: https://github.com/ambv/black
    rev: 23.10.1
    hooks:
      - id: black
        args: [--line-length=120]
        language_version: python3.9

  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.10
    hooks:
      - id: vulture
        types: [python]
        pass_filenames: false
        require_serial: true

  - repo: https://github.com/pycqa/pylint
    rev: v3.0.1
    hooks:
      - id: pylint
        args: [--disable=all, --enable=unused-import]
        language_version: python3.9

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.4.1
  #   hooks:
  #     - id: mypy
  #       exclude: (^tests/)|(vulture_whitelist.py)|(^docs/)
  #       args: [--strict]
  #       additional_dependencies: [numpy, pandas-stubs, ch5mpy, types-tqdm]
  #       language_version: python3.10
