site_name: VData
site_url: https://vdata.doc.com

nav:
  - VData: 'index.md'
  - Overview:
    - Summary: 'overview/index.md'
    - Time point: 'overview/timepoint.md'
    - TemporalDataFrame: 'overview/tdf.md'
    - VData: 'overview/vdata.md'
    - Compatibility with the scverse: 'overview/compatibility.md'
  - How-To guides: 'how_to.md'
  - API documentation:
      - VData: 'api/vdata.md'
      - TimePoint: 'api/timepoint.md'
      - RepeatingIndex: 'api/repeating_index.md'
  - Topics:
    - 'topics/hdf5.md'
  - About:
    - 'about/license.md'

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - content.code.copy
    - content.code.select
  language: en
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
      primary: custom
      accent: custom

    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
      primary: custom
      accent: custom

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to system preference
      primary: custom
      accent: custom
  navigation_depth: 1

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Vidium/vdata

extra_css:
  - stylesheets/extra.css

plugins:
  - mkdocstrings

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.details
  - pymdownx.superfences
  - toc

