[tool.ruff]
line-length = 120

[tool.mypy]
strict = true
namespace_packages = true

[[tool.mypy.overrides]]
module = [
    'pandas',
    'scipy',
    'anndata',
    'pympler',
    'scipy.sparse',
    'numpy_indexed',
    'h5py'
]
ignore_missing_imports = true
